# Generated by Django 4.1.3 on 2023-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("krw", "Won"), ("usd", "Dollar")], default="won", max_length=5
            ),
        ),
    ]
