# Generated by Django 4.1.3 on 2022-12-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_rename_price_house_price_for_night"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="price_for_night",
            new_name="price_per_night",
        ),
    ]
