# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_rename_price_for_night_house_price_per_night"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(default=False, help_text="당신은 애완동물을 사랑합니까?"),
        ),
    ]
