# Generated by Django 4.1.3 on 2022-12-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perk",
            name="Explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="perk",
            name="detail",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
